vich_uploader:
    db_driver: orm 

    mappings:
        cours_image:
            uri_prefix: uploads/images/cours
            upload_destination: '%kernel.project_dir%/public/uploads/images/cours'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        galerie_image:
            uri_prefix: uploads/images/galerie
            upload_destination: '%kernel.project_dir%/public/uploads/images/galerie'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        home_image:
            uri_prefix: uploads/images/home
            upload_destination: '%kernel.project_dir%/public/uploads/images/home'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            